name: tests
on: [pull_request]

jobs:
  run:
    name: 🚀 Test
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🚀 Run
        shell: bash
        run: |
          cd laboratories/cicd-documentation
          python3 -m unittest unit_tests.py
